### ISSUE TITLE
it require changing IP address continuously ?

### ISSUE THREAD

**Issue by alauthor** [0xfff0800/Brute-force-gmail#12]
what is the best solution of this problem .
plz help ,

Traceback (most recent call last):
  File "/Users/admin/Desktop/Brute-force-gmail/gmail-3.py", line 79, in <module>
    instance.try_gmail()
  File "/Users/admin/Desktop/Brute-force-gmail/gmail-3.py", line 33, in try_gmail
    self.smtp.login(user,password)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 734, in login
    (code, resp) = self.auth(
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 637, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 427, in docmd
    return self.getreply()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 400, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by 0xfff0800** [comment]
The problem has been resolved
